name: NPM Publishing

on:
  push:
    tags: ['v*.*.*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # For provenance

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type checking
      run: npx tsc --noEmit
      
    - name: Run tests
      run: npm run test:coverage
      
    - name: Build project
      run: npm run build
      
    - name: Verify package contents
      run: |
        echo "Package contents:"
        npm pack --dry-run
        
    - name: Check working directory is clean
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Working directory is not clean"
          git status --porcelain
          exit 1
        fi
        
    - name: Publish to npm with provenance
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
